version: '3.9'
services:
  # PHP-FPM Service
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    # Mounts the local 'app' directory to the container's Nginx root
      - ./:/var/www/html  
    depends_on:
    # Depends on the MySQL database service
      - mysql-db  

  # NGINX Service
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
    # Mountlocal 'app' directory to the Nginx root
      - ./:/var/www/html 
    ports:
      - "8080:80"
    depends_on:
      - php-fpm  # Depends on the PHP-FPM service
      - mysql-db  # Depends on the MySQL database service

  # MySQL Database Service
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todoapi
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
    # Maps port 3306 on the host to port 3306 on the MySQL container
      - "3306:3306"  

  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql-db